# Generated by Django 2.2.10 on 2021-05-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=250)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('publishedAt', models.DateTimeField()),
                ('thumbnailsUrls', models.URLField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
